import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import QueryProvider from "@/components/queryProvider";
import EdgeProvider from "@/components/edgestoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <QueryProvider>
      <EdgeProvider>
    <html lang="en">
      <body className={inter.className} >{children}
      <Toaster />
      </body>
    </html>
    </EdgeProvider>
    </QueryProvider>
    </ClerkProvider>
  );
}
